cli:
  api_key: some-key-here
  # server: https://fossa.on-prem

analyze:
  - name: fossa-cli
    path: github.com/fossas/fossa-cli/cmd/fossa
    type: gopackage
  # - name: vendored-jquery
  #   path: vendor/jquery-stuff/bower.json
  #   type: bowerpackage

# These take a lot of inspiration from CircleCI
# build:
#   working_directory: /fossa
#   docker:
#     - image: some-image-host/image-name
#       auth:
#         username: foo
#         password: $BAR
#   environment:
#     key: value
#   steps: |
#     echo "test"
#     ls