builds:
  - main: ./cmd/fossa/
    binary: fossa
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X github.com/fossas/fossa-cli/cmd/fossa/version.Version={{.Version}} -X github.com/fossas/fossa-cli/cmd/fossa/version.Commit={{.Commit}} -X "github.com/fossas/fossa-cli/cmd/fossa/version.GoVersion={{.Env.GOVERSION}}" -X github.com/fossas/fossa-cli/cmd/fossa/version.BuildType=production
