version: 2
jobs:
  build:
    docker:
      - image: quay.io/fossa/fossa-cli:latest
    working_directory: /home/fossa/go/src/github.com/fossas/fossa-cli
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - restore_cache:
          keys:
            - gopkg-cache-{{ checksum "Gopkg.lock" }}
      - run:
          name: Compile CLI
          command: |
            # Invalidate pkg cache for FOSSA CLI binary
            rm -rf pkg/linux_amd64/github.com/fossas/fossa-cli
            dep ensure
            make
      - run:
          name: Run integration test
          command: |
            go test ./build

      - save_cache:
          key: gopkg-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - "/home/fossa/go/pkg"

      - store_test_results:
          path: /tmp/test-results